from python_scraper.get_raw_jobs_data import get_jobs_data
from python_scraper.add_tech_stack_labels import add_tech_stack_labels
from python_scraper.create_tech_stack_rank import create_tech_stack_rank
from python_scraper.create_tech_stack_rank import create_tech_stack_rank_by_company
from python_scraper.create_tech_stack_rank import update_landing_summary

get_jobs_data()
add_tech_stack_labels()
create_tech_stack_rank()
create_tech_stack_rank_by_company()
update_landing_summary()
