name: Build and deploy Python project to Azure Function App - jobsScraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write       # ⭐️ 必须有这行
  contents: read 

env:
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # 只需要登录 Azure，然后直接部署
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CD6E75B241364F7EA13CEA7A14181200 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_62798EA4C2434996A8EB79C53FBB8B0A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6B7AD870CCCB4440B4614F909363232E }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'jobsScraper'
          slot-name: 'Production'
          package: .